# https://platform.openai.com/docs/pricing

VanillaOpenAIFramework:
  - task: "ner"
    n_runs: 1
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "o4-mini-2025-04-16"
      llm_model_host: "openai"
      source_data_pickle_path: "data/resume_data.pkl"
      description_path: "/home/bch/Project/main_project/resume/llm-structured-output-benchmarks/data/schema.json"

  - task: "ner"
    n_runs: 1
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4.1-nano-2025-04-14"
      llm_model_host: "openai"
      source_data_pickle_path: "data/resume_data.pkl"
      description_path: "/home/bch/Project/main_project/resume/llm-structured-output-benchmarks/data/schema.json"

  - task: "ner"
    n_runs: 1
    init_kwargs:
      prompt: "Extract and resolve a list of entities from the following text: {text}"
      llm_model: "gpt-4o-mini-2024-07-18"
      llm_model_host: "openai"
      source_data_pickle_path: "data/resume_data.pkl"
      description_path: "/home/bch/Project/main_project/resume/llm-structured-output-benchmarks/data/schema.json"